BrewBlox/brewblox-ui

package-lock.json, package.json
webpack is failing in 0.15.2, revert back to `quasar-cli@next`
=> Revert to quasar-cli@next

mocks/api/blocks/list/GET.json, src/core/fetch.ts, src/store/blocks/api.test.ts, src/store/blocks/api.ts
Branched from #30 <- should be merged first so I can shrink this PR
=> Refactor block API response to handle `data`

src/components/widget-modal/widget-types.ts, src/components/widgets/Metrics/CreateMetrics.vue, src/store/blocks/OneWireTempSensor/getters.ts, src/store/blocks/Pid/Pid.d.ts, src/store/blocks/Pid/actions.ts, src/store/blocks/Pid/getters.ts, src/store/blocks/SensorSetPointPair/SensorSetPointPair.d.ts, src/store/blocks/SensorSetPointPair/getters.ts, src/store/blocks/SetPointSimple/SetPointSimple.d.ts, src/store/blocks/SetPointSimple/getters.ts, src/store/blocks/actions.ts, src/store/blocks/api.ts, src/store/blocks/getters.ts
blocks/getters now implements templated functions for getting 1/all blocks of a type.
getters for each block only fill the template, and add the typeName string.
=> implement generic blockById and allBlocksFromService functions

src/components/Wizard/NewServiceWizard.vue, src/plugins/history/HistoryWizard.vue, src/plugins/history/store/actions.ts, src/plugins/history/store/api.ts, src/plugins/spark/provider/SparkWizard.vue, src/plugins/spark/store/actions.ts, src/plugins/spark/store/api.ts
=> validate spark and history services on creation

src/plugins/history/features/Graph/GraphForm.vue, src/plugins/spark/features/SetpointProfile/SetpointProfileForm.vue, src/quasar.ts
=> Add "now" button to datetime elements

src/components/Grid/GridItem.vue, src/components/Widget/EditWidget.vue, src/components/Widget/WidgetBase.ts, src/components/Widget/WidgetCard.vue, src/components/Widget/WidgetToolbar.vue, src/pages/DashboardPage.vue, src/plugins/spark/features/ActuatorPin/ActuatorPinForm.vue, src/plugins/spark/features/ActuatorPin/index.ts, src/plugins/spark/provider/SparkPage.vue, src/store/dashboards/getters.ts
=> Implement delete and copy on spark page

src/plugins/spark/components/BlockWizard.vue
=> Autosuggest block ID in block wizard

src/plugins/spark/provider/SparkWidget.vue, src/plugins/spark/store/actions.ts
=> Add button for discovering blocks

src/plugins/spark/features/Pid/PidWidget.vue
Also fixed:
- confirm/cancel buttons on input fields
=> Implement card title as static, slide only card-main

src/components/Widget/EditableNumber.vue, src/components/Widget/UnitPopupEdit.vue, src/plugins/spark/components/BlockWidget.ts, src/plugins/spark/features/Pid/PidWidget.vue
Refactored unit edit input into component for re-use in many widgets and dialogs
=> Unit popup edit component

src/components/Widget/DatetimePopupEdit.vue, src/components/Widget/InputPopupEdit.vue, src/components/Widget/SelectPopupEdit.vue, src/components/Widget/UnitPopupEdit.vue, src/components/Widget/WidgetBase.ts, src/pages/DashboardPage.vue, src/plugins/spark/features/Pid/PidWidget.vue, src/plugins/spark/provider/SparkPage.vue, src/store/dashboards/actions.ts
Proof of concept implemented in new PID widget
=> Allow renaming widgets

src/pages/DashboardPage.vue, src/store/dashboards/actions.ts, vue.config.js
=> Improve dashboard renaming flow; fix dashboard change errors

docker/amd/Dockerfile, docker/arm/Dockerfile, docker/conf/default.conf
=> forward all nginx requests to brewblox SPA

.gitignore, docker-compose.yml, package.json, src/plugins/spark/store/actions.ts, src/plugins/spark/store/getters.ts, src/plugins/spark/store/mutations.ts, src/store/dashboards/actions.ts, src/store/dashboards/getters.ts, src/store/dashboards/mutations.ts, src/store/features/actions.ts, src/store/features/getters.ts, src/store/features/mutations.ts, src/store/history/actions.ts, src/store/history/getters.ts, src/store/history/mutations.ts, src/store/providers/actions.ts, src/store/providers/getters.ts, src/store/providers/mutations.ts, src/store/services/actions.ts, src/store/services/getters.ts, src/store/services/mutations.ts, src/store/vuex-key-fix.ts, vue.config.js
=> explicitly set vuexkey

src/components/Widget/SelectPopupEdit.vue, src/plugins/spark/components/BlockForm.ts, src/plugins/spark/features/ActuatorAnalogMock/ActuatorAnalogMockForm.vue, src/plugins/spark/features/ActuatorOffset/ActuatorOffsetForm.vue, src/plugins/spark/features/ActuatorPin/ActuatorPinForm.vue, src/plugins/spark/features/ActuatorPwm/ActuatorPwmForm.vue, src/plugins/spark/features/Balancer/BalancerForm.vue, src/plugins/spark/features/Mutex/MutexForm.vue, src/plugins/spark/features/Pid/PidForm.vue, src/plugins/spark/features/SetpointProfile/SetpointProfileForm.vue, src/plugins/spark/features/SetpointSensorPair/SetpointSensorPairForm.vue, src/plugins/spark/features/SetpointSimple/SetpointSimpleForm.vue, src/plugins/spark/features/TempSensorMock/TempSensorMockForm.vue, src/plugins/spark/features/TempSensorOneWire/TempSensorOneWireForm.vue
=> Allow multiple presets in component forms

src/plugins/history/Graph/GraphForm.vue, src/plugins/history/Graph/GraphWizard.vue, src/plugins/spark/components/BlockForm.ts, src/plugins/spark/components/BlockGraph.vue, src/plugins/spark/components/BlockWizard.vue, src/plugins/spark/features/ActuatorAnalogMock/ActuatorAnalogMockForm.vue, src/plugins/spark/features/ActuatorOffset/ActuatorOffsetForm.vue, src/plugins/spark/features/ActuatorPin/ActuatorPinForm.vue, src/plugins/spark/features/ActuatorPwm/ActuatorPwmForm.vue, src/plugins/spark/features/Balancer/BalancerForm.vue, src/plugins/spark/features/InactiveObject/InactiveObjectForm.vue, src/plugins/spark/features/Mutex/MutexForm.vue, src/plugins/spark/features/Pid/PidForm.vue, src/plugins/spark/features/SetpointProfile/SetpointProfileForm.vue, src/plugins/spark/features/SetpointSensorPair/SetpointSensorPairForm.vue, src/plugins/spark/features/SetpointSimple/SetpointSimpleForm.vue, src/plugins/spark/features/TempSensorMock/TempSensorMockForm.vue, src/plugins/spark/features/TempSensorOneWire/TempSensorOneWireForm.vue, src/plugins/spark/provider/SparkForm.vue
=> Add close button to modals

src/plugins/spark/components/BlockForm.ts, src/plugins/spark/components/NewBlockWizard.vue, src/plugins/spark/provider/SparkPage.vue
=> Add block-only creation

src/plugins/spark/index.ts, src/plugins/spark/provider/SparkWidget.vue, src/plugins/spark/store/actions.ts, src/plugins/spark/store/api.ts, src/plugins/spark/store/getters.ts, src/plugins/spark/store/index.ts, src/plugins/spark/store/mutations.ts, src/plugins/spark/store/state.d.ts
=> use SSE instead of timed updates

src/components/Graph/GraphDisplay.vue, src/components/Widget/EditWidget.vue, src/components/Widget/InputPopupEdit.vue, src/components/Widget/InvalidWidget.vue, src/components/Widget/LinkPopupEdit.vue, src/components/Widget/SelectPopupEdit.vue, src/helpers/database.ts, src/layouts/DefaultLayout.vue, src/pages/DashboardPage.vue, src/plugins/history/Graph/GraphWidget.vue, src/plugins/spark/components/GenericBlock/GenericBlock.vue, src/plugins/spark/features/ActuatorAnalogMock/ActuatorAnalogMockWidget.vue, src/plugins/spark/features/ActuatorOffset/ActuatorOffsetWidget.vue, src/plugins/spark/features/ActuatorPin/ActuatorPinWidget.vue, src/plugins/spark/features/ActuatorPwm/ActuatorPwmWidget.vue, src/plugins/spark/features/Balancer/BalancerWidget.vue, src/plugins/spark/features/InactiveObject/InactiveObjectWidget.vue, src/plugins/spark/features/Mutex/MutexWidget.vue, src/plugins/spark/features/Pid/PidWidget.vue, src/plugins/spark/features/SetpointProfile/SetpointProfileWidget.vue, src/plugins/spark/features/SetpointSensorPair/SetpointSensorPairWidget.vue, src/plugins/spark/features/SetpointSimple/SetpointSimpleWidget.vue, src/plugins/spark/features/TempSensorMock/TempSensorMockWidget.vue, src/plugins/spark/features/TempSensorOneWire/TempSensorOneWireWidget.vue, src/plugins/spark/index.ts, src/plugins/spark/provider/SparkWidget.vue, src/store/dashboards/actions.ts, src/store/dashboards/api.ts, src/store/services/api.ts
=> Truncate input fields at 30 characters; async plotly

src/plugins/spark/features/ProcessView/ProcessViewWizard.vue, src/plugins/spark/features/ProcessView/index.ts
=> add simple wizard

src/pages/IndexPage.vue
=> Switch to primary dashboard whenever available

src/App.vue, src/helpers/database.ts, src/store/dashboards/actions.ts, src/store/dashboards/api.ts, src/store/dashboards/getters.ts, src/store/dashboards/index.ts, src/store/dashboards/mutations.ts, src/store/dashboards/state.d.ts, src/store/services/actions.ts, src/store/services/api.ts, src/store/services/getters.ts, src/store/services/index.ts, src/store/services/state.d.ts
=> retry database synchronization

src/layouts/DefaultLayout.vue
=> Always display add dashboard / service button if empty

src/components/Graph/GraphCard.vue, src/plugins/spark/components/BlockGraph.vue, src/plugins/spark/provider/SparkPage.vue
=> locally keep track of widget config in spark page

dev/presets/dashboard-items.json, src/components/Graph/GraphCard.vue, src/components/Graph/functional.ts, src/components/Widget/DatetimePopupEdit.vue, src/components/Widget/FormBase.ts, src/components/Widget/WidgetBase.ts, src/plugins/history/Graph/GraphForm.vue, src/plugins/history/Graph/GraphWidget.vue, src/plugins/spark/components/BlockGraph.vue, src/plugins/spark/features/ProcessView/index.ts, src/plugins/spark/features/ProcessView/state.d.ts, src/plugins/spark/features/SessionView/SessionViewForm.vue, src/plugins/spark/features/SessionView/SessionViewWidget.vue, src/plugins/spark/features/SessionView/SessionViewWizard.vue, src/plugins/spark/features/SessionView/index.ts, src/plugins/spark/features/SessionView/state.d.ts, src/plugins/spark/features/index.ts, src/plugins/spark/index.ts, src/store/history/state.d.ts
=> implement session view widget

dev/presets/services.json, dev/presets/spark_blocks.json, src/plugins/spark/components/BlockSettings.vue, src/plugins/spark/components/BlockWizard.vue, src/plugins/spark/components/GroupsPopupEdit.vue, src/plugins/spark/components/NewBlockWizard.vue, src/plugins/spark/features/InactiveObject/InactiveObjectWidget.vue, src/plugins/spark/index.ts, src/plugins/spark/provider/SparkForm.vue, src/plugins/spark/provider/getters.ts, src/plugins/spark/provider/state.d.ts, src/plugins/spark/state.d.ts, src/plugins/spark/store/actions.ts, src/plugins/spark/store/api.ts, src/plugins/spark/store/getters.ts
=> rename profiles to groups; reserve 7 for system
